# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('suggest', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='App.Music')),
                ('music_user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
        ),
    ]
