# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-16 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_orders_user_response'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='App_orders',
        ),
    ]
