"""
Django settings for CloudMusic project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9jpj+-tv$-ycufkvdh=x#)m#tv+m%m895kogwuo&%xqd$j3y8s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App.apps.AppConfig',
    'Admin',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CloudMusic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        'environment': 'CloudMusic.jinja2.environment',
        },
    },
]

WSGI_APPLICATION = 'CloudMusic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'music_db',
        'HOST':'127.0.0.1',
        'USER':'root',
        'PORT':'3306',
        'PASSWORD':'123456',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]




#阿里云短信验证码配置
SMSCONFIG = {
    'ACCESS_KEY_ID':"LTAI0cJ2nTIsIjsx",
    'ACCESS_KEY_SECRET':"rR7yyMRREKC2zVuozTpanMKKtSmn43",
    'SignName':"django",
    'TemplateCode':"SMS_172221952"
}


# 文件上传路径
MEDIA_ROOT=os.path.join(BASE_DIR,'static/uplod')#绝对路径
# 上传文件格式
PHOTO_STYLE=['png','jpeg','jpg','gif']
# 上传文件大小最大10M
MAX_FILE_SIZE=10*1024*1024




#邮件发送设置
# smtp服务的邮箱服务器器
EMAIL_HOST = 'smtp.163.com'
#发送邮件的邮箱
EMAIL_HOST_USER = 'ky19980204@163.com'
#在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'ky19980108'
#收件人人看到的发件人人 <此处要和发送邮件的邮箱相同>
EMAIL_FROM = 'python<ky19980204@163.com>'


#分页配置
# 每页记录个数
COUNTOFPAGE = 8
#每页的页码范围
PAGERANGE = 10